openapi: 3.0.1
info:
  title: public api
  version: 1.0.0
paths:
  /pipo/consumers/{tenant}:
    post:
      operationId: createConsumer
      summary: create consumer
      parameters:
        - name: tenant
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
  /pipo/consumers/{login}:
    delete:
      operationId: deleteConsumer
      summary: delete consumer
      parameters:
        - name: login
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: OK

components:
  schemas:
    RegisterRequest:
      type: object
      required: [ env ]
      properties:
        env:
          $ref: '#/components/schemas/Environment'
    RegisterResponse:
      type: object
      properties:
        login:
          type: string
          example: "123abc"
        password:
          type: string
          example: "password123"
    Environment:
      type: string
      enum:
        - DEV
        - PROD