server:
  port: 8080
  servlet:
    context-path: /

spring:
  config:
    import: optional:file:.env
  application:
    name: pipo

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml