server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: pipo

  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USER}